spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:whatsmine;MODE=MySQL;DB_CLOSE_DELAY=-1}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.whatsmine: INFO
    org.springframework.web: INFO

